# TOKENS LIST
tokens = [
    #ARITMETIC OPERATORS
    'ADICION',
    'SUBSTRACCION',
    'MULTIPLICACION',
    'DIVISION',
    'MODULO',
    'ASIGNACION'

    #OPERADORES DE COMPARACION RELACIONAL
    'MENORQ',
    'MENOROIGUAL',
    'MAYORQ',
    'MAYOROIGUAL',

    # OPERADORES DE COMPARACION DE IGUALDAD
    'DIFERENTE',
    'DOBLEIGUAL',

    #OPERADORES LOGICOS
    'OR',
    'AND',

    #OPERADORES UNARIOS
    'CAMBIOSIGNO',
    'NEGACIONLOGICA',

    #DATOS
    'TABULAR',
    'NUEVALINEA',
    'CADENA',

    #TIPOS DE NUMEROS
    'HEXAGEXIMAL',
    'ENTERO',
]
